export default function(VueRouter){
	return new VueRouter({
		
		routes:[
			{
				path:"",
				component:require('../view/view.vue'),
				children:[
					{
						path:"",
						components:{
							default:require('../view/index.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"index",
						components:{
							default:require('../view/index.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"news",
						components:{
							default:require('../view/news.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"news/:id",
						components:{
							default:require('../view/news.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"register",
						components:{
							default:require('../view/register.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"login",
						components:{
							default:require('../view/login.vue'),
							header:require('../view/header.vue')
						}
					}
				]
			},
			{
				path:"/index",
				component:require('../view/view.vue'),
				children:[
					{
						path:"",
						components:{
							default:require('../view/index.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"index",
						components:{
							default:require('../view/index.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"news",
						components:{
							default:require('../view/news.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"news/:id",
						components:{
							default:require('../view/news.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"register",
						components:{
							default:require('../view/register.vue'),
							header:require('../view/header.vue')
						}
					},
					{
						path:"login",
						components:{
							default:require('../view/login.vue'),
							header:require('../view/header.vue')
						}
					}
				]	
			},
			{
				path:"/index/detailed/:id",
				component:require('../view/detailed.vue'),
				children: [
			  		{path:"",component:require('../view/newsType.vue')}
			  	]
			},
			{
				path:"/detailed/:id",
				component:require('../view/detailed.vue'),
				children: [
			  		{path:"",component:require('../view/newsType.vue')}
			  	]
			},
			{
				path:"/discuss/:id",
				component:require('../view/discuss.vue')	
			},
			{
				path:"/index/discuss/:id",
				component:require('../view/discuss.vue')	
			},
			{
				path:"/replaceDiscuss/:id",
				component:require('../view/replaceDiscuss.vue')	
			},
			{
				path:"/index/replaceDiscuss/:id",
				component:require('../view/replaceDiscuss.vue')	
			}
			/*
			{
				path:"",
				component:require('../view/view.vue'),

				children: [
					{path:"",component:require('../view/index.vue')},
			  		{path:"index",component:require('../view/index.vue')},
			  		{path:"login",component:require('../view/login.vue')},
			  		{path:"news",component:require('../view/news.vue')},
			  		{path:"news/:id",component:require('../view/news.vue')},
			  		{path:"register",component:require('../view/register.vue')},
			  		{path:"detailed/:id",
			  			component:require('../view/detailed.vue'),
			  			props:["headerFlg"],
			  			children: [
			  				{path:"",components:require('../view/newsType.vue')}
			  			]
			  		}
			  	]
			},
			{
				path:"/index",
			  	component:require('../view/view.vue'),
			  	
			  	children: [
			  		{path:"",component:require('../view/index.vue')},
			  		{path:"index",component:require('../view/index.vue')},
			  		{path:"login",component:require('../view/login.vue')},
			  		{path:"news",component:require('../view/news.vue')},
			  		{path:"news/:id",component:require('../view/news.vue')},
			  		{path:"register",component:require('../view/register.vue')},
			  		{path:"detailed/:id",component:require('../view/detailed.vue'),
			  		props:["headerFlg"],
			  			children: [
			  				{path:"",component:require('../view/newsType.vue')}
			  			]
			  		}
			  	]
			}*/
		]
	})
}